apiVersion: apps/v1
kind: Deployment 
metadata:
  name: koa-kube-app
  labels: 
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: koa-kube
        image: coolsteam/koa-app:v1
        ports:
        - containerPort: 3000

